### ISSUE TITLE
Support http/2

### ISSUE THREAD

**Issue by lucianojs** [chengsun/moz-spdy-indicator#14]
I suggest add support http/2 protocol like a similar plugin on chrome
https://chrome.google.com/webstore/detail/spdy-indicator/mpbpobfflnpcgagjijhmgnchggcjblin

**Comment by chengsun** [comment]
Hi @lucianojs,
This should have already been added by PR https://github.com/chengsun/moz-spdy-indicator/pull/12.
Can you give a specific example of a website on which this doesn't work?
Cheers.

**Comment by lucianojs** [comment]
I try www.google.com.br and the plugin shows spdy 3.1. 
My browser is Firefox ESR 31.4.0 and had set the flag network.http.spdy.enabled.http2draft to true.

When I try the same site in Chrome the plugin shows http2 support.

**Comment by chengsun** [comment]
Hi @lucianojs,
This is not a problem with moz-spdy-indicator.
Unfortunately the issue is that HTTP/2 has undergone many drafts, each incompatible with the previous. *Firefox 31 only implements HTTP/2 draft 10*, which has been outdated for a while now. Google only supports the latest (draft 14), which is incompatible. If you really need to test HTTP/2 support, you will have to update to at least Firefox 34.
Cheers.
