### ISSUE TITLE
e10s compatibility

### ISSUE THREAD

**Issue by sweoggy** [chengsun/moz-spdy-indicator#21]
According to my Firefox 48.0.2 (release) this addon doesn't support e10s despite earlier efforts to make it compatible (c73d5336518307c6c5c16ee0f502b80a7bae001d). It would be great if complete support could be added since this functionality isn't far off from getting standardised now.

![http2 indicator incompatible](https://cloud.githubusercontent.com/assets/5914253/18198020/b4aba66e-70fa-11e6-8757-ff05b50570ac.PNG)

**Comment by ArchangeGabriel** [comment]
What’s the status here?

**Comment by chengsun** [comment]
Sorry, this add-on is not actively being maintained. If you have a patch to fix the problem I would be more than happy to merge it in.

**Comment by chengsun** [comment]
One would need to investigate whether the new WebExtension API gives us the information we need.

**Comment by gena01** [comment]
I think it checks a flag in the install.rdf to see if addon suppports e10s or not.

**Comment by bsiegel** [comment]
This addon currently depends on the compatibility shims provided by Firefox, which means that it does work under e10s mode and starting from Firefox 51, does not prevent multiprocess from being enabled. However, this means that the addon will continue to appears with "Add-on Multi Process Status: Unknown" in AMO.

Since Firefox is going all-in on WebExtensions starting in v57, this will eventually be resolved by a future WebExtension version of this addon. I'm going to look into porting the Google Chrome HTTP/2 addon when I have some time.
